### PR TITLE
fix: display filename in gcodeviewer

### LINKED ISSUE #868: Gcode viewer - no file name on page
### Requested feature:

file name on gcode viewer page.....latest beta.

### Solves the following problem:

wich file?

### Additional information:

thanks!

### PR DESCRIPTION
**Pull request by meteyou**
fixed #868 

Signed-off-by: Stefan Dej <meteyou@gmail.com>

### CODE REVIEW

File: src/components/gcodeviewer/Viewer.vue [hunk 1]
```diff
@@ -43,11 +43,7 @@
 
 <template>
     <div>
-        <panel
-            :title="$t('GCodeViewer.Title')"
-            :icon="mdiVideo3d"
-            card-class="gcode-viewer-panel"
-            :margin-bottom="false">
+        <panel :title="panelTitle" :icon="mdiVideo3d" card-class="gcode-viewer-panel" :margin-bottom="false">
```
Comment (th33xitus) [inline src/components/gcodeviewer/Viewer.vue:46]:
```suggestion
        <panel :title="panelTitle.toString()" :icon="mdiVideo3d" card-class="gcode-viewer-panel" :margin-bottom="false">
```
this will prevent a weak IDE warning

File: src/components/gcodeviewer/Viewer.vue [hunk 2]
```diff
@@ -405,6 +401,14 @@ export default class Viewer extends Mixins(BaseMixin) {
         })
     }
 
+    get panelTitle() {
+        let title = this.$t('GCodeViewer.Title')
+
+        if (this.loadedFile) title += ': ' + this.loadedFile
```
Comment (th33xitus) [inline src/components/gcodeviewer/Viewer.vue:407]:
```suggestion
        if (this.loadedFile) title += `: ${this.loadedFile}`
```
String interpolation > String concatenation

**Review by th33xitus — CHANGES_REQUESTED** [review]

**Review by th33xitus — APPROVED** [review]
